name: kib_debug_print
description: A Flutter package that provides enhanced debug printing capabilities with timestamps, counters, and categorized logging functionality.
version: 1.0.0
repository: https://github.com/kibmuikia/kib_debug_print
issue_tracker: https://github.com/kibmuikia/kib_debug_print/issues
documentation: https://github.com/kibmuikia/kib_debug_print#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# This package only contains Dart code and doesn't require any additional Flutter-specific configuration
flutter:
# This section intentionally left empty as the package doesn't use any assets or fonts
